kind: ConfigMap
apiVersion: v1
metadata:
  name: spending-service
data:
  application.properties: |-
    server.port=8080
    logging.level.root=INFO
    spring.sleuth.sampler.probability=1.0
    spring.cloud.gcp.logging.enabled=true
    spring.cloud.kubernetes.reload.enabled=true
    spring.cloud.gcp.credentials.location=file:/etc/secrets/google/key.json
  application-dev.properties: |-
    spring.profiles=dev
    server.error.include-stacktrace=always
  application-prod.properties: |-
    spring.profiles=prod
    server.error.include-stacktrace=never
    logging.level.root=ERROR
    spring.devtools.add-properties=false