kind: ConfigMap
apiVersion: v1
metadata:
  name: spending-service
data:
  application.properties: |-
    app.gcp.projectId=test-project-292914
    app.gcp.subscription-name=add-spending-v1-worker
    app.gcp.keyPath=${GOOGLE_APPLICATION_CREDENTIALS}
    server.port=8080
    logging.level.root=INFO
    spring.datasource.url=jdbc:h2:mem:testdb
    spring.datasource.driverClassName=org.h2.Driver
    spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
    spring.sleuth.sampler.probability=1.0
    spring.cloud.gcp.logging.enabled=true
    ---
    spring.profiles=dev
    server.error.include-stacktrace=always
    ---
    spring.profiles=prod
    server.error.include-stacktrace=never
    logging.level.root=ERROR