kind: ConfigMap
apiVersion: v1
metadata:
  name: spending-service
data:
  application.properties: |-
    app.gcp.keyPath=/var/secrets/google/key.json
    app.gcp.projectId=test-project-292914
    server.port=8080
    logging.level.root=INFO
    ---
    spring.profiles=development
    test.message=Dev
    ---
    spring.profiles=production
    test.message=Prod